[versions]
kotlin = "1.7.21"

minecraft = "1.19.3"
qfapi = "5.0.0-alpha.3+0.68.1-1.19.3"
qkl = "1.0.0+kt.1.7.20+flk.1.8.5"
loader = "0.18.1-beta.23"
mappings = "1.19.3+build.1"
loom = "1.+"
energy = "2.3.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
qfapi = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "qfapi" }
qfapi_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "qfapi" }


qkl = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "qkl"}
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "mappings" }

energy = {module = "teamreborn:energy", version.ref = "energy"}
[bundles]
quilted_fabric_api = ["qfapi", "qfapi_deprecated"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "loom" }
